### PR TITLE
show limited amount of pages

### PR DESCRIPTION
**Pull request by DanielW1987**
The pagination component now shows dot items on more than 10 pages.

### CODE REVIEW

**Comment by DanielW1987** [comment]
[Pagination: Show limited amount of pages](https://trello.com/c/Sh6LG713/198-pagination-show-limited-amount-of-pages)

**Review by hedgehog1833 — APPROVED** [review]
GEFN but there is still an issue when there are many pages. Spotify's api documentation states that the offset when searching has a maximum value of 2000 ([see here](https://developer.spotify.com/documentation/web-api/reference/search/search/)). For offsets > 2000 we get 404.

**Comment by DanielW1987** [comment]
> GEFN but there is still an issue when there are many pages. Spotify's api documentation states that the offset when searching has a maximum value of 2000 ([see here](https://developer.spotify.com/documentation/web-api/reference/search/search/)). For offsets > 2000 we get 404.

For what artist I have to search to reproduce this?

**Comment by hedgehog1833** [comment]
Just type in incomplete name. I started with `Ope` or just type `a`

**Comment by DanielW1987** [comment]
will have a look at it...

**Pull request merged**
